### ISSUE TITLE
[project-config] add redux-sagas

### ISSUE THREAD

**Issue by ortonomy** [ortonomy/flingapp#8]
# justification
I've been looking a lot at asynchronous side effects -- sending mutations to the backend, loading data into state management using redux, and I've had some experience using redux-sagas.

I really like the way it works, it's _extremely_ simple to understand and makes some good use of ES6 generator functions to handle async in a sync looking way.  It's also all based on promises.

# how-to
https://github.com/redux-saga/redux-saga

**Comment by xuyuji9000** [comment]
How's this feature going?

**Comment by ortonomy** [comment]
Abandoned in favour of redux-logic
